/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ChatSessionStatus = { 'cancelled' : null } |
  { 'completed' : null } |
  { 'inProgress' : null } |
  { 'archived' : null };
export type ConfidenceLevel = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface HelpMessage {
  'id' : ID,
  'content' : string,
  'sender' : MessageSender,
  'messageType' : MessageType,
  'timestamp' : Time,
}
export interface HelpSessionView {
  'id' : ID,
  'status' : ChatSessionStatus,
  'principal' : Principal,
  'messages' : Array<HelpMessage>,
  'startAt' : Time,
  'lastUpdated' : Time,
  'confidenceLevel' : [] | [ConfidenceLevel],
  'followUps' : Array<string>,
}
export type ID = bigint;
export type MessageSender = { 'user' : null } |
  { 'systemMessage' : null } |
  { 'assistant' : null };
export type MessageType = { 'question' : null } |
  { 'diagnosticStep' : null } |
  { 'safetyAlert' : null } |
  { 'text' : null } |
  { 'answer' : null } |
  { 'measurementEntry' : null } |
  { 'recommendation' : null } |
  { 'educationalTip' : null };
export interface OnboardingPayload { 'screens' : Array<OnboardingScreen> }
export interface OnboardingScreen {
  'title' : string,
  'icon' : string,
  'description' : string,
}
export interface Progress {
  'completedChapters' : Array<bigint>,
  'masteryScore' : bigint,
}
export type StudyMode = { 'beginner' : null } |
  { 'expert' : null };
export type Time = bigint;
export interface UserProfile {
  'id' : ID,
  'name' : string,
  'email' : string,
  'company' : string,
  'experienceYears' : bigint,
  'progress' : Progress,
  'studyMode' : StudyMode,
  'phone' : string,
  'certifications' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addHelpMessage' : ActorMethod<[HelpMessage], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCurrentHelpSession' : ActorMethod<[], undefined>,
  'clearHelpMessages' : ActorMethod<[], undefined>,
  'finishHelpSession' : ActorMethod<[], undefined>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentHelpMessages' : ActorMethod<[], Array<HelpMessage>>,
  'getFollowUps' : ActorMethod<[], Array<string>>,
  'getHelpMessages' : ActorMethod<[], Array<HelpMessage>>,
  'getHelpSession' : ActorMethod<[], [] | [HelpSessionView]>,
  'getOnboardingPayload' : ActorMethod<[], OnboardingPayload>,
  'getUserProfile' : ActorMethod<[], UserProfile>,
  'getUserProfileByPrincipal' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'initializeUserProfile' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isWalkthroughCompleted' : ActorMethod<[], boolean>,
  'markWalkthroughCompleted' : ActorMethod<[], undefined>,
  'removeUserProfile' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startHelpSession' : ActorMethod<[], undefined>,
  'updateHelpSession' : ActorMethod<
    [Array<HelpMessage>, Array<string>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];