/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ID = IDL.Nat;
export const MessageSender = IDL.Variant({
  'user' : IDL.Null,
  'systemMessage' : IDL.Null,
  'assistant' : IDL.Null,
});
export const MessageType = IDL.Variant({
  'question' : IDL.Null,
  'diagnosticStep' : IDL.Null,
  'safetyAlert' : IDL.Null,
  'text' : IDL.Null,
  'answer' : IDL.Null,
  'measurementEntry' : IDL.Null,
  'recommendation' : IDL.Null,
  'educationalTip' : IDL.Null,
});
export const Time = IDL.Int;
export const HelpMessage = IDL.Record({
  'id' : ID,
  'content' : IDL.Text,
  'sender' : MessageSender,
  'messageType' : MessageType,
  'timestamp' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Progress = IDL.Record({
  'completedChapters' : IDL.Vec(IDL.Nat),
  'masteryScore' : IDL.Nat,
});
export const StudyMode = IDL.Variant({
  'beginner' : IDL.Null,
  'expert' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : ID,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'experienceYears' : IDL.Nat,
  'progress' : Progress,
  'studyMode' : StudyMode,
  'phone' : IDL.Text,
  'certifications' : IDL.Vec(IDL.Text),
});
export const ChatSessionStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
  'archived' : IDL.Null,
});
export const ConfidenceLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const HelpSessionView = IDL.Record({
  'id' : ID,
  'status' : ChatSessionStatus,
  'principal' : IDL.Principal,
  'messages' : IDL.Vec(HelpMessage),
  'startAt' : Time,
  'lastUpdated' : Time,
  'confidenceLevel' : IDL.Opt(ConfidenceLevel),
  'followUps' : IDL.Vec(IDL.Text),
});
export const OnboardingScreen = IDL.Record({
  'title' : IDL.Text,
  'icon' : IDL.Text,
  'description' : IDL.Text,
});
export const OnboardingPayload = IDL.Record({
  'screens' : IDL.Vec(OnboardingScreen),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addHelpMessage' : IDL.Func([HelpMessage], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCurrentHelpSession' : IDL.Func([], [], []),
  'clearHelpMessages' : IDL.Func([], [], []),
  'finishHelpSession' : IDL.Func([], [], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentHelpMessages' : IDL.Func([], [IDL.Vec(HelpMessage)], ['query']),
  'getFollowUps' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getHelpMessages' : IDL.Func([], [IDL.Vec(HelpMessage)], ['query']),
  'getHelpSession' : IDL.Func([], [IDL.Opt(HelpSessionView)], ['query']),
  'getOnboardingPayload' : IDL.Func([], [OnboardingPayload], ['query']),
  'getUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getUserProfileByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'initializeUserProfile' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isWalkthroughCompleted' : IDL.Func([], [IDL.Bool], ['query']),
  'markWalkthroughCompleted' : IDL.Func([], [], []),
  'removeUserProfile' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setUserProfile' : IDL.Func([UserProfile], [], []),
  'startHelpSession' : IDL.Func([], [], []),
  'updateHelpSession' : IDL.Func(
      [IDL.Vec(HelpMessage), IDL.Vec(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ID = IDL.Nat;
  const MessageSender = IDL.Variant({
    'user' : IDL.Null,
    'systemMessage' : IDL.Null,
    'assistant' : IDL.Null,
  });
  const MessageType = IDL.Variant({
    'question' : IDL.Null,
    'diagnosticStep' : IDL.Null,
    'safetyAlert' : IDL.Null,
    'text' : IDL.Null,
    'answer' : IDL.Null,
    'measurementEntry' : IDL.Null,
    'recommendation' : IDL.Null,
    'educationalTip' : IDL.Null,
  });
  const Time = IDL.Int;
  const HelpMessage = IDL.Record({
    'id' : ID,
    'content' : IDL.Text,
    'sender' : MessageSender,
    'messageType' : MessageType,
    'timestamp' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Progress = IDL.Record({
    'completedChapters' : IDL.Vec(IDL.Nat),
    'masteryScore' : IDL.Nat,
  });
  const StudyMode = IDL.Variant({ 'beginner' : IDL.Null, 'expert' : IDL.Null });
  const UserProfile = IDL.Record({
    'id' : ID,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'experienceYears' : IDL.Nat,
    'progress' : Progress,
    'studyMode' : StudyMode,
    'phone' : IDL.Text,
    'certifications' : IDL.Vec(IDL.Text),
  });
  const ChatSessionStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
    'archived' : IDL.Null,
  });
  const ConfidenceLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const HelpSessionView = IDL.Record({
    'id' : ID,
    'status' : ChatSessionStatus,
    'principal' : IDL.Principal,
    'messages' : IDL.Vec(HelpMessage),
    'startAt' : Time,
    'lastUpdated' : Time,
    'confidenceLevel' : IDL.Opt(ConfidenceLevel),
    'followUps' : IDL.Vec(IDL.Text),
  });
  const OnboardingScreen = IDL.Record({
    'title' : IDL.Text,
    'icon' : IDL.Text,
    'description' : IDL.Text,
  });
  const OnboardingPayload = IDL.Record({
    'screens' : IDL.Vec(OnboardingScreen),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addHelpMessage' : IDL.Func([HelpMessage], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCurrentHelpSession' : IDL.Func([], [], []),
    'clearHelpMessages' : IDL.Func([], [], []),
    'finishHelpSession' : IDL.Func([], [], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentHelpMessages' : IDL.Func([], [IDL.Vec(HelpMessage)], ['query']),
    'getFollowUps' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getHelpMessages' : IDL.Func([], [IDL.Vec(HelpMessage)], ['query']),
    'getHelpSession' : IDL.Func([], [IDL.Opt(HelpSessionView)], ['query']),
    'getOnboardingPayload' : IDL.Func([], [OnboardingPayload], ['query']),
    'getUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getUserProfileByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'initializeUserProfile' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isWalkthroughCompleted' : IDL.Func([], [IDL.Bool], ['query']),
    'markWalkthroughCompleted' : IDL.Func([], [], []),
    'removeUserProfile' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setUserProfile' : IDL.Func([UserProfile], [], []),
    'startHelpSession' : IDL.Func([], [], []),
    'updateHelpSession' : IDL.Func(
        [IDL.Vec(HelpMessage), IDL.Vec(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };