/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface HelpMessage {
    id: ID;
    content: string;
    sender: MessageSender;
    messageType: MessageType;
    timestamp: Time;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface OnboardingScreen {
    title: string;
    icon: string;
    description: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface HelpSessionView {
    id: ID;
    status: ChatSessionStatus;
    principal: Principal;
    messages: Array<HelpMessage>;
    startAt: Time;
    lastUpdated: Time;
    confidenceLevel?: ConfidenceLevel;
    followUps: Array<string>;
}
export type ID = bigint;
export interface Progress {
    completedChapters: Array<bigint>;
    masteryScore: bigint;
}
export interface OnboardingPayload {
    screens: Array<OnboardingScreen>;
}
export interface UserProfile {
    id: ID;
    name: string;
    email: string;
    company: string;
    experienceYears: bigint;
    progress: Progress;
    studyMode: StudyMode;
    phone: string;
    certifications: Array<string>;
}
export enum ChatSessionStatus {
    cancelled = "cancelled",
    completed = "completed",
    inProgress = "inProgress",
    archived = "archived"
}
export enum ConfidenceLevel {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum MessageSender {
    user = "user",
    systemMessage = "systemMessage",
    assistant = "assistant"
}
export enum MessageType {
    question = "question",
    diagnosticStep = "diagnosticStep",
    safetyAlert = "safetyAlert",
    text = "text",
    answer = "answer",
    measurementEntry = "measurementEntry",
    recommendation = "recommendation",
    educationalTip = "educationalTip"
}
export enum StudyMode {
    beginner = "beginner",
    expert = "expert"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addHelpMessage(message: HelpMessage): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearCurrentHelpSession(): Promise<void>;
    clearHelpMessages(): Promise<void>;
    finishHelpSession(): Promise<void>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentHelpMessages(): Promise<Array<HelpMessage>>;
    getFollowUps(): Promise<Array<string>>;
    getHelpMessages(): Promise<Array<HelpMessage>>;
    getHelpSession(): Promise<HelpSessionView | null>;
    getOnboardingPayload(): Promise<OnboardingPayload>;
    getUserProfile(): Promise<UserProfile>;
    getUserProfileByPrincipal(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    initializeUserProfile(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isWalkthroughCompleted(): Promise<boolean>;
    markWalkthroughCompleted(): Promise<void>;
    removeUserProfile(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setUserProfile(profile: UserProfile): Promise<void>;
    startHelpSession(): Promise<void>;
    updateHelpSession(messagesToAdd: Array<HelpMessage>, followupsToAdd: Array<string>): Promise<void>;
}
import type { ChatSessionStatus as _ChatSessionStatus, ConfidenceLevel as _ConfidenceLevel, HelpMessage as _HelpMessage, HelpSessionView as _HelpSessionView, ID as _ID, MessageSender as _MessageSender, MessageType as _MessageType, Progress as _Progress, StudyMode as _StudyMode, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addHelpMessage(arg0: HelpMessage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addHelpMessage(to_candid_HelpMessage_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHelpMessage(to_candid_HelpMessage_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearCurrentHelpSession(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCurrentHelpSession();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCurrentHelpSession();
            return result;
        }
    }
    async clearHelpMessages(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearHelpMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearHelpMessages();
            return result;
        }
    }
    async finishHelpSession(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.finishHelpSession();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.finishHelpSession();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentHelpMessages(): Promise<Array<HelpMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentHelpMessages();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentHelpMessages();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowUps(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowUps();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowUps();
            return result;
        }
    }
    async getHelpMessages(): Promise<Array<HelpMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHelpMessages();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHelpMessages();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHelpSession(): Promise<HelpSessionView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHelpSession();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHelpSession();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOnboardingPayload(): Promise<OnboardingPayload> {
        if (this.processError) {
            try {
                const result = await this.actor.getOnboardingPayload();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOnboardingPayload();
            return result;
        }
    }
    async getUserProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_UserProfile_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_UserProfile_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfileByPrincipal(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfileByPrincipal(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfileByPrincipal(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async initializeUserProfile(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeUserProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeUserProfile();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isWalkthroughCompleted(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isWalkthroughCompleted();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isWalkthroughCompleted();
            return result;
        }
    }
    async markWalkthroughCompleted(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markWalkthroughCompleted();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markWalkthroughCompleted();
            return result;
        }
    }
    async removeUserProfile(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeUserProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeUserProfile();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserProfile(to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserProfile(to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async startHelpSession(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startHelpSession();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startHelpSession();
            return result;
        }
    }
    async updateHelpSession(arg0: Array<HelpMessage>, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHelpSession(to_candid_vec_n43(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHelpSession(to_candid_vec_n43(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
}
function from_candid_ChatSessionStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatSessionStatus): ChatSessionStatus {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_ConfidenceLevel_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConfidenceLevel): ConfidenceLevel {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_HelpMessage_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HelpMessage): HelpMessage {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_HelpSessionView_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HelpSessionView): HelpSessionView {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_MessageSender_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageSender): MessageSender {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_MessageType_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageType): MessageType {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_StudyMode_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudyMode): StudyMode {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HelpSessionView]): HelpSessionView | null {
    return value.length === 0 ? null : from_candid_HelpSessionView_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ConfidenceLevel]): ConfidenceLevel | null {
    return value.length === 0 ? null : from_candid_ConfidenceLevel_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ID;
    name: string;
    email: string;
    company: string;
    experienceYears: bigint;
    progress: _Progress;
    studyMode: _StudyMode;
    phone: string;
    certifications: Array<string>;
}): {
    id: ID;
    name: string;
    email: string;
    company: string;
    experienceYears: bigint;
    progress: Progress;
    studyMode: StudyMode;
    phone: string;
    certifications: Array<string>;
} {
    return {
        id: value.id,
        name: value.name,
        email: value.email,
        company: value.company,
        experienceYears: value.experienceYears,
        progress: value.progress,
        studyMode: from_candid_StudyMode_n19(_uploadFile, _downloadFile, value.studyMode),
        phone: value.phone,
        certifications: value.certifications
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ID;
    content: string;
    sender: _MessageSender;
    messageType: _MessageType;
    timestamp: _Time;
}): {
    id: ID;
    content: string;
    sender: MessageSender;
    messageType: MessageType;
    timestamp: Time;
} {
    return {
        id: value.id,
        content: value.content,
        sender: from_candid_MessageSender_n27(_uploadFile, _downloadFile, value.sender),
        messageType: from_candid_MessageType_n29(_uploadFile, _downloadFile, value.messageType),
        timestamp: value.timestamp
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ID;
    status: _ChatSessionStatus;
    principal: Principal;
    messages: Array<_HelpMessage>;
    startAt: _Time;
    lastUpdated: _Time;
    confidenceLevel: [] | [_ConfidenceLevel];
    followUps: Array<string>;
}): {
    id: ID;
    status: ChatSessionStatus;
    principal: Principal;
    messages: Array<HelpMessage>;
    startAt: Time;
    lastUpdated: Time;
    confidenceLevel?: ConfidenceLevel;
    followUps: Array<string>;
} {
    return {
        id: value.id,
        status: from_candid_ChatSessionStatus_n34(_uploadFile, _downloadFile, value.status),
        principal: value.principal,
        messages: from_candid_vec_n24(_uploadFile, _downloadFile, value.messages),
        startAt: value.startAt,
        lastUpdated: value.lastUpdated,
        confidenceLevel: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.confidenceLevel)),
        followUps: value.followUps
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    beginner: null;
} | {
    expert: null;
}): StudyMode {
    return "beginner" in value ? StudyMode.beginner : "expert" in value ? StudyMode.expert : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: null;
} | {
    systemMessage: null;
} | {
    assistant: null;
}): MessageSender {
    return "user" in value ? MessageSender.user : "systemMessage" in value ? MessageSender.systemMessage : "assistant" in value ? MessageSender.assistant : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    question: null;
} | {
    diagnosticStep: null;
} | {
    safetyAlert: null;
} | {
    text: null;
} | {
    answer: null;
} | {
    measurementEntry: null;
} | {
    recommendation: null;
} | {
    educationalTip: null;
}): MessageType {
    return "question" in value ? MessageType.question : "diagnosticStep" in value ? MessageType.diagnosticStep : "safetyAlert" in value ? MessageType.safetyAlert : "text" in value ? MessageType.text : "answer" in value ? MessageType.answer : "measurementEntry" in value ? MessageType.measurementEntry : "recommendation" in value ? MessageType.recommendation : "educationalTip" in value ? MessageType.educationalTip : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    completed: null;
} | {
    inProgress: null;
} | {
    archived: null;
}): ChatSessionStatus {
    return "cancelled" in value ? ChatSessionStatus.cancelled : "completed" in value ? ChatSessionStatus.completed : "inProgress" in value ? ChatSessionStatus.inProgress : "archived" in value ? ChatSessionStatus.archived : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): ConfidenceLevel {
    return "low" in value ? ConfidenceLevel.low : "high" in value ? ConfidenceLevel.high : "medium" in value ? ConfidenceLevel.medium : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HelpMessage>): Array<HelpMessage> {
    return value.map((x)=>from_candid_HelpMessage_n25(_uploadFile, _downloadFile, x));
}
function to_candid_HelpMessage_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HelpMessage): _HelpMessage {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_MessageSender_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageSender): _MessageSender {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_MessageType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageType): _MessageType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_StudyMode_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudyMode): _StudyMode {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ID;
    name: string;
    email: string;
    company: string;
    experienceYears: bigint;
    progress: Progress;
    studyMode: StudyMode;
    phone: string;
    certifications: Array<string>;
}): {
    id: _ID;
    name: string;
    email: string;
    company: string;
    experienceYears: bigint;
    progress: _Progress;
    studyMode: _StudyMode;
    phone: string;
    certifications: Array<string>;
} {
    return {
        id: value.id,
        name: value.name,
        email: value.email,
        company: value.company,
        experienceYears: value.experienceYears,
        progress: value.progress,
        studyMode: to_candid_StudyMode_n41(_uploadFile, _downloadFile, value.studyMode),
        phone: value.phone,
        certifications: value.certifications
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ID;
    content: string;
    sender: MessageSender;
    messageType: MessageType;
    timestamp: Time;
}): {
    id: _ID;
    content: string;
    sender: _MessageSender;
    messageType: _MessageType;
    timestamp: _Time;
} {
    return {
        id: value.id,
        content: value.content,
        sender: to_candid_MessageSender_n10(_uploadFile, _downloadFile, value.sender),
        messageType: to_candid_MessageType_n12(_uploadFile, _downloadFile, value.messageType),
        timestamp: value.timestamp
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageSender): {
    user: null;
} | {
    systemMessage: null;
} | {
    assistant: null;
} {
    return value == MessageSender.user ? {
        user: null
    } : value == MessageSender.systemMessage ? {
        systemMessage: null
    } : value == MessageSender.assistant ? {
        assistant: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageType): {
    question: null;
} | {
    diagnosticStep: null;
} | {
    safetyAlert: null;
} | {
    text: null;
} | {
    answer: null;
} | {
    measurementEntry: null;
} | {
    recommendation: null;
} | {
    educationalTip: null;
} {
    return value == MessageType.question ? {
        question: null
    } : value == MessageType.diagnosticStep ? {
        diagnosticStep: null
    } : value == MessageType.safetyAlert ? {
        safetyAlert: null
    } : value == MessageType.text ? {
        text: null
    } : value == MessageType.answer ? {
        answer: null
    } : value == MessageType.measurementEntry ? {
        measurementEntry: null
    } : value == MessageType.recommendation ? {
        recommendation: null
    } : value == MessageType.educationalTip ? {
        educationalTip: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudyMode): {
    beginner: null;
} | {
    expert: null;
} {
    return value == StudyMode.beginner ? {
        beginner: null
    } : value == StudyMode.expert ? {
        expert: null
    } : value;
}
function to_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<HelpMessage>): Array<_HelpMessage> {
    return value.map((x)=>to_candid_HelpMessage_n8(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
